# Generated by Django 4.2.7 on 2023-11-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
