# Generated by Django 4.2.7 on 2023-11-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('createcomp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualitative_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_factor', models.FloatField(default=3)),
                ('cost_of_equity', models.FloatField(default=0.5)),
                ('discount_to_trading_mults', models.FloatField(default=0.5)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createcomp.company')),
            ],
        ),
    ]
