# Generated by Django 4.2.7 on 2023-11-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('createcomp', '0002_company_last_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualitative_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createcomp.company')),
            ],
        ),
    ]
