# Generated by Django 4.2.7 on 2023-11-15 19:02

from django.db import migrations, models
import peers.beta
import peers.customsales
import peers.financialstructure


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ev_sales', peers.customsales.CustomSalesField()),
                ('ev_ebit', peers.customsales.CustomSalesField()),
                ('ev_ebitda', peers.customsales.CustomSalesField()),
                ('p_e', peers.customsales.CustomSalesField()),
                ('financial_strucutre', peers.financialstructure.FinancialStructureField()),
                ('beta', peers.beta.BetaField()),
            ],
        ),
    ]
