# Generated by Django 4.2.7 on 2023-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccompany',
            name='beta',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='publiccompany',
            name='ev_ebit',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='publiccompany',
            name='ev_ebitda',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='publiccompany',
            name='ev_sales',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='publiccompany',
            name='financial_strucutre',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='publiccompany',
            name='p_e',
            field=models.JSONField(),
        ),
    ]
