# Generated by Django 4.2.7 on 2023-11-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peers', '0002_alter_publiccompany_beta_alter_publiccompany_ev_ebit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publiccompany',
            old_name='financial_strucutre',
            new_name='financial_structure',
        ),
    ]
